stages:
    - build
    - test


build laptop:
   image: alpine
   stage: build
   script:
     - echo "Building a laptop"
     - mkdir build
     - touch build/computer.txt
     - echo "Mainboard" >> build/computer.txt
     - cat build/computer.txt
     - echo "Keyboard" >> build/computer.txt
     - cat build/computer.txt
     - echo "Samandar" >> build.computer.txt
     - cat build/computer.txt
   artifacts:
       paths:
           - build

test laptop:
   stage: test
   image: alpine
   script:
     - test -f build/computer.txt
