# Generated by Django 4.0.3 on 2022-05-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
