# Generated by Django 4.0.3 on 2022-05-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_customer_phone_alter_customer_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.CharField(max_length=13)),
                ('digital', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/')),
            ],
        ),
    ]
