# Generated by Django 4.0.3 on 2022-05-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=2249735, max_length=11),
            preserve_default=False,
        ),
    ]
