# Generated by Django 4.0.4 on 2022-05-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_orderitem_customer_order_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pict',
            field=models.ImageField(blank=True, null=True, upload_to='store/'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
