# Generated by Django 4.0.4 on 2022-05-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_customer_profile_pict_alter_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='profile_pict',
            new_name='image',
        ),
    ]
